# Generated by Django 3.1.1 on 2020-11-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='fecha',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='plan_de_pago',
            field=models.CharField(max_length=10),
        ),
    ]
